### ISSUE TITLE
Publicação na Apple Store

### ISSUE THREAD

**Issue by ItaloRod** [EscolaDeSaudePublica/isus-app#21]
Essa é a mensagem que eles enviaram
Binário Recusado   
  4. 2 Design: Minimum Functionality

Guideline 4.2.2 - Design - Minimum Functionality

We still noticed that your app only includes links, images, or content aggregated from the Internet with limited or no native iOS functionality. Although this content may be curated from the web specifically for your users, since it does not sufficiently differ from a mobile web browsing experience, it is not appropriate for the App Store.

Next Steps

We encourage you to review your app concept and work towards creating an app that offers customers an engaging and lasting experience that also meets the App Store’s high expectations for quality and functionality.

Apple Developer includes a variety of design and development resources. Download iOS templates from Apple UI Design Resources, learn more about crafting intuitive, well-designed apps with the Design Video collection, and review the iOS Human Interface Guidelines for best practices to follow when designing apps for the App Store.

**Comment by uira** [comment]
Perfeito. Eles tão reclamando que é só um esqueleto, e agora vamos melhorar isso.

Vamos submeter novamente, na próxima versão.

**Comment by ItaloRod** [comment]
https://developer.apple.com/design/resources/

**Comment by uira** [comment]
## Nova resposta para a versão 2.4.1:

21 de mai de 2020 às 16:36
### De Apple
2. 1 Performance: App Completeness
4. Design: Preamble
Guideline 2.1 - Information Needed

We have started the review of your app, but we are not able to continue because we need additional information about the functionality and services in your app related to the COVID-19 pandemic.

Next Steps

To help us proceed with the review of your app, please provide detailed responses to the following questions. The more information you can provide at this time, the sooner we can complete your review.

- What permissions does the app ask for (location, bluetooth, contacts, HealthKit, Clinical Health Records etc.) and what are the permissions strings for each? If necessary, please provide English translations of the permission string.
- Are these permissions required or optional?
- Are there other uses of these permissions besides those listed in the permission string?
- What personal information does the app require? List each separately with reasons why it’s required.
- What personal information is optional? List each separately with reasons why the app is requesting it.
- Who in your organization has access to the information you collect?
- Is any of this data shared with any other parties? If so, provide details.
- Beyond the permissions already described, what other disclosures and user consent steps does the app contain?
- What jurisdiction(s) (i.e. region, state, country, etc.) is this app intended for?
- Has this app been authorized for use by the government of that jurisdiction?
- Is this the sole app authorized to provide COVID-19 related services in this jurisdiction?
- Is the jurisdiction this app is intended for use in expected to change or expand?
- Is the use of any features of this app mandatory in these jurisdictions?
- If so, what are the consequences and other options available to individuals in the jurisdiction that cannot or do not install the app?
- Will you be applying for and transitioning this app to use the Exposure Notification APIs?
- Do you plan to remove any app with quarantine management or contact tracing functionality from the App Store once the need for those apps has passed (i.e. once the COVID-19 pandemic is over)?

If your app is contributing to or conducting research related to the COVID-19 pandemic, please provide detailed answers to these additional questions:

- Provide proof of approval from an independent ethics review board.
- Provide steps to locate the disclosure and consent mechanisms required under 5.1.3(iii). If done outside of the app before the user receives login credentials, provide the associated consent forms.

Once you reply to this message in Resolution Center with the requested information, we can proceed with your review.

Guideline 4.0 - Design


We noticed that several screens of your app were crowded or laid out in a way that made it difficult to use your app.

Next Steps

To resolve this issue, please revise your app to ensure that the content and controls on the screen are easy to read and interact with.

Resources

For more information, please review the following resources on the iOS Developer Center page:

- UI Do's and Don'ts

- iOS Human Interface Guidelines

- UIKit

Please see screenshot below for details:

![image](https://user-images.githubusercontent.com/89998/82693714-5f592200-9c38-11ea-8041-1637327292dd.png)

**Comment by uira** [comment]
Nova resposta enviada:

Hello Apple Team,

First of all, we to not introduce ourselves properly: we are the official developer team for The School of Public Health of Ceará - ESP / CE, created by Law No. 12,140, of July 22, 1993, with competence redefined in accordance with item IV of art. 78 of Law No. 13,875, of February 7, 2007, and restructured in accordance with Decree No. 30,602, of July 15, 2011.

It is an entity of the About the bug, this has already been fixed. State Administration, of an autarkic nature, linked to the Secretariat of Health of Ceará - SESA, governed by its own regulation, internal rules and the relevant legislation in force. (our website: https://www.esp.ce.gov.br/)

About the bug, this has already been fixed. Thanks for that.

- What permissions does the app ask for (location, bluetooth, contacts, HealthKit, Clinical Health Records etc.) and what are the permissions strings for each? If necessary, please provide English translations of the permission string.
A: No, it doesnt.


- Are these permissions required or optional?
A: no.


- Are there other uses of these permissions besides those listed in the permission string?
A: no


- What personal information does the app require? List each separately with reasons why it’s required.
A: Nothing.


- What personal information is optional? List each separately with reasons why the app is requesting it.
A: Nos aplicable.


- Who in your organization has access to the information you collect?
R: We dont collect.


- Is any of this data shared with any other parties? If so, provide details.
A: Dont.


- Beyond the permissions already described, what other disclosures and user consent steps does the app contain?
A: Nothing.


- What jurisdiction(s) (i.e. region, state, country, etc.) is this app intended for?
Ceará State of Brasil.


- Has this app been authorized for use by the government of that jurisdiction?
A: Yes, ESP has the function of relationship and permanent education of health professionals in the state of Ceara.

- Is this the sole app authorized to provide COVID-19 related services in this jurisdiction?
A: If need be, it will be autorized.


- Is the jurisdiction this app is intended for use in expected to change or expand?
A: Not for now.

- Is the use of any features of this app mandatory in these jurisdictions?
A: Not for now.


- If so, what are the consequences and other options available to individuals in the jurisdiction that cannot or do not install the app?
A: not for now.

- Will you be applying for and transitioning this app to use the Exposure Notification APIs?
A: No, never.

- Do you plan to remove any app with quarantine management or contact tracing functionality from the App Store once the need for those apps has passed (i.e. once the COVID-19 pandemic is over)?
A: not aplicable.


Thanks!!

**Comment by uira** [comment]
# De Apple
### 26 de mai de 2020 às 06:14
2. 1 Performance: App Completeness
Hello,

Thank you for your reply and for the information provided.

Your app’s review will require additional time as we take this new information into account. We do not require any further information about your app at this time.

Once we have thoroughly reviewed your app, we will either contact you in Resolution Center to communicate any issues found, or your app will be approved.

Best regards,

**Comment by uira** [comment]
<img width="411" alt="Google Pixel 2 XL - 1" src="https://user-images.githubusercontent.com/89998/83238765-4c30df80-a16d-11ea-8af8-4242ceb38dd3.png">
<img width="411" alt="Google Pixel 2 XL - 2" src="https://user-images.githubusercontent.com/89998/83238779-4fc46680-a16d-11ea-8e67-967ff95ecb3a.png">
<img width="411" alt="Google Pixel 2 XL - 3" src="https://user-images.githubusercontent.com/89998/83238780-505cfd00-a16d-11ea-864a-acfc247f341d.png">
<img width="411" alt="Google Pixel 2 XL - 4" src="https://user-images.githubusercontent.com/89998/83238782-50f59380-a16d-11ea-89e9-342b2cfbce8e.png">
<img width="411" alt="Google Pixel 2 XL - 5" src="https://user-images.githubusercontent.com/89998/83238784-518e2a00-a16d-11ea-8eed-59c295835678.png">

![image](https://user-images.githubusercontent.com/89998/83238796-5521b100-a16d-11ea-9d27-fe8d6e5c9f75.png)

![image](https://user-images.githubusercontent.com/89998/83238816-5bb02880-a16d-11ea-826f-9464fc92a868.png)
